### ISSUE TITLE
Inclusion of code coverage - NYC

### ISSUE THREAD

**Issue by piyushchauhan2011** [eddyerburgh/avoriaz-ava-example#8]
I was wondering is it possible to add in the code coverage using nyc, it would be very helpful @eddyerburgh

**Comment by piyushchauhan2011** [comment]
Finally got it working might send a pull request if all good ;)

**Comment by eddyerburgh** [comment]
Nice! 😄  

Could you make a PR and add nyc to the example?

**Comment by piyushchauhan2011** [comment]
Awesome @eddyerburgh 😃  Opened a pull for inclusion

**Comment by piyushchauhan2011** [comment]
Hi @eddyerburgh I was wondering if you give a try to Nuxt.js and if it's possible to include avoriaz+nyc+ava coverage there also ?

**Comment by eddyerburgh** [comment]
@piyushchauhan2011 I'm busy for the next week, but I could have a look after 👍 

Not sure why using ava and avoriaz would cause the server to run infinitely?

**Comment by piyushchauhan2011** [comment]
Hey @eddyerburgh, all good 💯  No worries. Yeah, I don't know, I might make a mock repo so that others can test it out too.
